#!/usr/bin/env python3
import sys, subprocess
from git_manager import *
import os
import argparse

def parse_args():

	parser = get_git_parser()
	opts, unknown = parser.parse_known_args()
	return (opts, unknown)

def main():
	validate_config()
	(opts, unknown) = parse_args()
	git_cmd = ['/usr/bin/git']
	args = sys.argv[1::]

	#subprocess.check_call(git_cmd)

	try:		
		git_cmd = git_cmd + args
		subprocess.check_call(git_cmd)
		if hasattr(opts, 'func'):
			opts.func(opts, unknown)

	except subprocess.CalledProcessError as git_exception:
		#print('Error ' + str(git_exception.returncode) + ' attempting to execute git ' + ' '.join(git_cmd[1::]))
		return git_exception.returncode

	return 0

if __name__ == "__main__":
   sys.exit(main())